import 'dart:io';

import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

/// WinUI C# 端 WindowsBridge.Codec 的 golden 向量测试。
///
/// 事实源是 Dart `StandardMethodCodec` 的真实编码字节：
/// - 常规运行：断言 `GoldenVectors.g.cs` 与当前 Dart 编码输出一致（防两端漂移）。
/// - `ONEPANEL_REGEN_GOLDEN=1` 运行：重新生成 `GoldenVectors.g.cs`。
///
/// ExpectedJson 是按 System.Text.Json 默认序列化约定手写的期望值，
/// 独立于 C# 代码路径，避免自证。
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  const goldenRelativePath =
      'windows/runner/native_host/OnePanelNativeHost.Tests/GoldenVectors.g.cs';

  test('WinUI C# golden vectors 与 Dart StandardMethodCodec 保持同步', () {
    final generated = _renderGoldenFile();
    final file = File(goldenRelativePath);

    if (Platform.environment['ONEPANEL_REGEN_GOLDEN'] == '1') {
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(generated);
      return;
    }

    expect(
      file.existsSync(),
      isTrue,
      reason: '缺少 $goldenRelativePath，'
          '请运行 ONEPANEL_REGEN_GOLDEN=1 flutter test '
          'test/core/channel/winui_codec_golden_test.dart 生成',
    );
    final onDisk = file.readAsStringSync().replaceAll('\r\n', '\n');
    expect(
      onDisk,
      generated,
      reason: 'GoldenVectors.g.cs 与 Dart StandardMethodCodec 当前输出不一致；'
          '若为预期变更，请运行 ONEPANEL_REGEN_GOLDEN=1 重新生成并同步 C# 侧',
    );
  });
}

// ── 用例表 ──────────────────────────────────────────────────────────────────

/// (方法名, Dart 参数值, C# 等价构造)
final _methodCallCases = <(String, Object?, String)>[
  ('getServers', null, 'null'),
  (
    'getFiles',
    <String, Object?>{'path': '/'},
    'new Dictionary<string, object?> { ["path"] = "/" }',
  ),
  ('getCurrentServer', null, 'null'),
  (
    'switchServer',
    <String, Object?>{'id': 'srv-001'},
    'new Dictionary<string, object?> { ["id"] = "srv-001" }',
  ),
  (
    'updateSetting',
    <String, Object?>{'key': 'app_lock_enabled', 'value': true},
    'new Dictionary<string, object?> { ["key"] = "app_lock_enabled", ["value"] = true }',
  ),
  (
    'codec.complex',
    <String, Object?>{
      'list': <Object?>[1, -5, 3000000000, 3.14, 'text', true, null],
      'nested': <String, Object?>{
        'inner': <Object?>[2, 3],
        'flag': false,
      },
    },
    'new Dictionary<string, object?> '
        '{ ["list"] = new List<object?> { 1, -5, 3000000000L, 3.14, "text", true, null }, '
        '["nested"] = new Dictionary<string, object?> '
        '{ ["inner"] = new List<object?> { 2, 3 }, ["flag"] = false } }',
  ),
];

/// (成功响应值, 手写期望 JSON —— System.Text.Json 默认约定)
final _successCases = <(Object?, String)>[
  (null, 'null'),
  (true, 'true'),
  (42, '42'),
  (-7, '-7'),
  (3000000000, '3000000000'),
  (3.14, '3.14'),
  ('ok', '"ok"'),
  (<Object?>[], '[]'),
  (<String, Object?>{}, '{}'),
  (
    <Object?>[
      <String, Object?>{
        'id': 'srv-001',
        'name': 'Production',
        'isCurrent': true,
        'cpu': 12.5,
      },
    ],
    '[{"id":"srv-001","name":"Production","isCurrent":true,"cpu":12.5}]',
  ),
  (
    <String, Object?>{'cpu': 1.5, 'memory': 2.5, 'load1': 0.4},
    '{"cpu":1.5,"memory":2.5,"load1":0.4}',
  ),
];

/// (错误码, 错误消息, details)
final _errorCases = <(String, String?, Object?)>[
  ('error', 'Missing method for channel call', null),
  ('server_error', 'upstream failed', 'ctx-1'),
];

// ── 生成逻辑 ────────────────────────────────────────────────────────────────

String _hex(ByteData data) {
  final bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  return bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
}

String _csString(String value) =>
    '"${value.replaceAll('\\', r'\\').replaceAll('"', r'\"')}"';

const _codec = StandardMethodCodec();

String _renderGoldenFile() {
  final sb = StringBuffer();
  sb.writeln('// <auto-generated>');
  sb.writeln('// 由 test/core/channel/winui_codec_golden_test.dart 生成'
      '（ONEPANEL_REGEN_GOLDEN=1），请勿手改。');
  sb.writeln('// Hex 为 Dart StandardMethodCodec 的真实编码字节，'
      '是 C# WindowsBridge.Codec 的 golden 向量。');
  sb.writeln('// </auto-generated>');
  sb.writeln('namespace OnePanelNativeHost.Tests;');
  sb.writeln();
  sb.writeln('public static class GoldenVectors');
  sb.writeln('{');

  sb.writeln('    public static readonly (string Name, string Hex)[] MethodCalls =');
  sb.writeln('    {');
  for (final (name, args, _) in _methodCallCases) {
    final bytes = _codec.encodeMethodCall(MethodCall(name, args));
    sb.writeln('        (${_csString(name)}, ${_csString(_hex(bytes))}),');
  }
  sb.writeln('    };');
  sb.writeln();

  sb.writeln('    public static readonly (string Name, string Hex, string ExpectedJson)[] SuccessResponses =');
  sb.writeln('    {');
  var successIndex = 0;
  for (final (value, expectedJson) in _successCases) {
    final bytes = _codec.encodeSuccessEnvelope(value);
    sb.writeln(
      '        (${_csString('success_$successIndex')}, '
      '${_csString(_hex(bytes))}, ${_csString(expectedJson)}),',
    );
    successIndex++;
  }
  sb.writeln('    };');
  sb.writeln();

  sb.writeln('    public static readonly (string Name, string Hex)[] ErrorResponses =');
  sb.writeln('    {');
  var errorIndex = 0;
  for (final (code, message, details) in _errorCases) {
    final bytes = _codec.encodeErrorEnvelope(code: code, message: message, details: details);
    sb.writeln('        (${_csString('error_$errorIndex')}, ${_csString(_hex(bytes))}),');
    errorIndex++;
  }
  sb.writeln('    };');
  sb.writeln('}');
  return sb.toString();
}
