// <auto-generated>
// 由 test/core/channel/winui_codec_golden_test.dart 生成（ONEPANEL_REGEN_GOLDEN=1），请勿手改。
// Hex 为 Dart StandardMethodCodec 的真实编码字节，是 C# WindowsBridge.Codec 的 golden 向量。
// </auto-generated>
namespace OnePanelNativeHost.Tests;

public static class GoldenVectors
{
    public static readonly (string Name, string Hex)[] MethodCalls =
    {
        ("getServers", "070a6765745365727665727300"),
        ("getFiles", "070867657446696c65730d0107047061746807012f"),
        ("getCurrentServer", "071067657443757272656e7453657276657200"),
        ("switchServer", "070c7377697463685365727665720d010702696407077372762d303031"),
        ("updateSetting", "070d75706461746553657474696e670d0207036b657907106170705f6c6f636b5f656e61626c6564070576616c756501"),
        ("codec.complex", "070d636f6465632e636f6d706c65780d0207046c6973740c07030100000003fbffffff04005ed0b200000000060000001f85eb51b81e0940070474657874010007066e65737465640d020705696e6e65720c02030200000003030000000704666c616702"),
    };

    public static readonly (string Name, string Hex, string ExpectedJson)[] SuccessResponses =
    {
        ("success_0", "0000", "null"),
        ("success_1", "0001", "true"),
        ("success_2", "00032a000000", "42"),
        ("success_3", "0003f9ffffff", "-7"),
        ("success_4", "0004005ed0b200000000", "3000000000"),
        ("success_5", "00060000000000001f85eb51b81e0940", "3.14"),
        ("success_6", "0007026f6b", "\"ok\""),
        ("success_7", "000c00", "[]"),
        ("success_8", "000d00", "{}"),
        ("success_9", "000c010d040702696407077372762d30303107046e616d65070a50726f64756374696f6e0709697343757272656e740107036370750600000000000000002940", "[{\"id\":\"srv-001\",\"name\":\"Production\",\"isCurrent\":true,\"cpu\":12.5}]"),
        ("success_10", "000d0307036370750600000000000000000000000000f83f07066d656d6f72790600000000000000000000000000044007056c6f616431069a9999999999d93f", "{\"cpu\":1.5,\"memory\":2.5,\"load1\":0.4}"),
    };

    public static readonly (string Name, string Hex)[] ErrorResponses =
    {
        ("error_0", "0107056572726f72071f4d697373696e67206d6574686f6420666f72206368616e6e656c2063616c6c00"),
        ("error_1", "01070c7365727665725f6572726f72070f757073747265616d206661696c656407056374782d31"),
    };
}
